name: .NET Build
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup MSBuild
      uses: warrenbuckley/Setup-MSBuild@v1
      env: ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    - name: Install dependencies
      run: msbuild -t:restore
    - name: Build project
      run: msbuild BeatStripper.sln /t:Build /p:Configuration=Release
    - name: Upload DLLs
      uses: actions/upload-artifact@v1
      with:
        name: BeatStripper-${{ github.sha }}
        path: ./BeatStripper/bin/Release
